version: '3.8'

services:
  aws:
    environment:
      DEBUG: 1
      LAMBDA_DOCKER_NETWORK: aws-network
      LAMBDA_REMOTE_DOCKER: 0
      SERVICES: lambda
    image: localstack/localstack:0.11.5 # ! 2020-10-11 v0.11.6 appears to be bugged for lambda
    networks:
      - aws-network
    ports:
      - 4566:4566
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  node-app:
    build: ./node-app
    environment:
      # * Lambda function name to invoke (found in dev.config) ---
      # LAMBDA_FUNCTIONNAME: go-lambda
      LAMBDA_FUNCTIONNAME: node-lambda
      # LAMBDA_FUNCTIONNAME: node-lambda-unique-handler
      # * ---
      AWS_ACCESSKEY_ID: can-be-anything
      AWS_ACCESSKEY_SECRETKEY: can-be-anything
      AWS_ENDPOINT: aws:4566
      AWS_REGION: us-east-1
      NODE_ENV: development
      NODE_NO_WARNINGS: 1 # * Supress warnings about unverified HTTPS connections
      NODE_TLS_REJECT_UNAUTHORIZED: 0 # * Connect via unverified HTTPS
    networks:
      - aws-network
    # volumes:
    #   - ./node-app:/app

networks:
  aws-network:
    name: aws-network
